
ifeq (,$(findstring -DCOCOA,$(CFLAGS)))
er-coap_src = er-coap.c er-coap-engine.c er-coap-transactions.c er-coap-observe.c er-coap-separate.c er-coap-res-well-known-core.c 
else
er-coap_src = er-coap.c er-coap-engine.c er-coap-transactions.c er-coap-observe.c er-coap-separate.c er-coap-res-well-known-core.c er-cocoa.c
endif


# Erbium will implement the REST Engine
CFLAGS += -DREST=coap_rest_implementation
